version: '2'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
  server:
    build: ./server
    restart: always
    environment:
      MONGODB_URI: mongodb://mongo/emask
      PORT: 80
    expose:
      - 80
    networks:
      - traefik
      - default
    labels:
      traefik.enable: true
      traefik.docker.network: "traefik"
      traefik.port: 80
      traefik.frontend.rule: Host:m.sheth.io;PathPrefix:/api/,/auth/,/callback/
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.STSPreload: true
      traefik.frontend.headers.STSSeconds: 2628000
      traefik.frontend.headers.STSIncludeSubdomains: true
    depends_on:
      - mongo
  frontend:
    build: ./client
    restart: always
    expose:
      - 80
    networks:
      - traefik
      - default
    labels:
      traefik.enable: true
      traefik.docker.network: "traefik"
      traefik.port: 80
      traefik.frontend.rule: Host:m.sheth.io
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.STSPreload: true
      traefik.frontend.headers.STSSeconds: 2628000
      traefik.frontend.headers.STSIncludeSubdomains: true

volumes:
  mongodata:

networks:
  traefik:
    external: true
